export type Prompt = {
  id: string;
  label: string;
  helper?: string;
  placeholder?: string;
  mode?: 'text' | 'long' | 'lines';
  targetCount?: number;
  minChars?: number;
  maxChars?: number;
};

export type Day = {
  day: number;
  stage: number;
  title: string;
  principle: string;
  output: string;
  prep: string[];
  prompts: Prompt[];
  checks: string[];
  externalAction?: string;
  sourcePages: string;
  editorialNote?: string;
};

export type Stage = {
  id: number;
  range: string;
  shortName: string;
  title: string;
  question: string;
  output: string;
};

export const stages: Stage[] = [
  {
    id: 1,
    range: '01—07',
    shortName: '一份清晰的服务说明',
    title: '说清你是谁、帮谁、为什么值钱',
    question: '一个陌生人能不能复述你解决什么问题？',
    output: '一份经过现实反馈的服务说明',
  },
  {
    id: 2,
    range: '08—14',
    shortName: '翻箱子，回答“我为什么信你”',
    title: '整理证据、故事和代表作品',
    question: '别人为什么愿意承担选择你的风险？',
    output: '一页“为什么能信我”',
  },
  {
    id: 3,
    range: '15—21',
    shortName: '与用户产生连接',
    title: '写出 5 篇说明价值的内容',
    question: '你的内容是否持续指向同一个价值？',
    output: '5 篇能够建立连接的内容',
  },
  {
    id: 4,
    range: '22—30',
    shortName: '一页购买入口',
    title: '做出一个可以被购买的入口',
    question: '合适的人看完以后，是否知道怎么买？',
    output: '一个可交付、可定价、可购买的最小产品',
  },
];

export const days: Day[] = [
  {
    day: 1,
    stage: 1,
    title: '先测一次：别人能不能听懂你的介绍',
    principle: '今天不预设你的介绍有问题，也不要求马上重写。先保存你真正使用的版本，再检查它有没有传达三项购买前必须知道的信息。已经说清楚的部分会保留；没说清楚的部分，接下来几天逐项补齐。',
    output: '你正在使用的介绍，以及“帮谁、解决什么、什么时候找你”的三项判断。',
    prep: ['你在主页、私信或口头介绍中最常使用的版本'],
    prompts: [
      {
        id: 'currentIntro',
        label: '粘贴你最近一次真实使用的自我介绍',
        helper: '可以是主页简介、第一次私信，或者你平时口头介绍自己的版本。请直接粘贴，不要为了完成练习临时改写。',
        placeholder: '例如：我是内容创作者，也做品牌咨询和小红书运营……',
        mode: 'long',
      },
    ],
    checks: ['已保存真实使用的版本', '已完成三项清晰度判断', '不要求为了完成任务强行找问题'],
    sourcePages: '250–251',
  },
  {
    day: 2,
    stage: 1,
    title: '你的客户是什么样的？',
    principle: '同一种能力可以服务很多人，但不同的人在意的问题、需要的证据和愿意购买的方式都不一样。今天不是确定终身定位，而是为这一次 30 天测试选一个主要客户；后面的痛点、证据、内容和产品都会先围绕这位客户来做。',
    output: '一组候选客户，以及这一轮先服务的一类人。',
    prep: ['你真实服务过的人', '你愿意长期接触的人', '你已有证据能帮助的人'],
    prompts: [
      {
        id: 'audienceCandidates',
        label: '先写 5 个你可能服务的人',
        helper: '每行写“一类人 + 正处在什么情况”。先写 5 个，有余力可以继续写到 10 个；没写满也能继续。',
        placeholder: '准备从公司转向自由职业的人\n已经开始提供咨询的独立顾问',
        mode: 'lines',
        targetCount: 5,
      },
      {
        id: 'selectedAudience',
        label: '写下你能帮到的客户是什么样的',
        helper: '其他候选不会丢失；这只是一个可以随时回来修改的临时方向。',
        mode: 'lines',
        targetCount: 1,
      },
    ],
    checks: ['已写出至少 1 个候选', '已选定唯一的主要客户', '后续任务只围绕这位客户展开'],
    sourcePages: '251–252',
  },
  {
    day: 3,
    stage: 1,
    title: '这类客户最想解决什么问题？',
    principle: '昨天确定的是“这次先服务谁”，今天确定的是“这类客户会因为什么具体情况来找你”。先写 5 条真实表达，有余力再写到 10 条，用来看出哪些问题反复出现。',
    output: '5–10 条真实问题，以及其中最值得先解决的 1–3 条。',
    prep: ['昨天确定的目标人群', '过往咨询、评论、聊天中出现过的原话'],
    prompts: [
      {
        id: 'problemCandidates',
        label: '请你代入这类客户，想想他们的卡点会是什么',
        helper: '结合你想提供的服务，想想对应解决了什么问题。可以多写几个，每行一个问题。',
        placeholder: '我不知道怎么介绍自己\n我发了很多内容，但没人来问\n【待验证】每次有人问价格，我都不知道该怎么报价',
        mode: 'lines',
        targetCount: 5,
      },
      {
        id: 'topProblems',
        label: '选出用户最痛的、你能解决的',
        helper: '从列出的卡点中选择 1–3 个。',
        mode: 'lines',
        targetCount: 3,
      },
    ],
    checks: ['已写出至少 1 条素材', '已选中 1–3 条', '推测内容已标记为待验证'],
    sourcePages: '252–253',
  },
  {
    day: 4,
    stage: 1,
    title: '拼接一句与你有关的自我介绍',
    principle: '目标客户和 3 个核心问题已经从前两天带进来。先选一个问题作为主轴，再写一句介绍；它的任务不是讲完整，而是让陌生人迅速判断“这和我的问题有没有关系”。',
    output: '5–10 个说法，以及当前最容易被复述的一版。',
    prep: ['目标客户', '3 个核心问题', '你能帮助客户往前推进的一步'],
    prompts: [
      {
        id: 'focusProblem',
        label: '选择他们正在遇到的问题',
        helper: '工具会直接使用 Day 3 的选择，不需要重新输入。',
        mode: 'lines',
        targetCount: 1,
      },
      {
        id: 'valueVersions',
        label: '生成、编辑并加入自我介绍候选池',
        helper: '每行一个。先写 5 个，有余力可以继续写到 10 个；一个也能继续。',
        placeholder: '我帮___，解决___，最终可以___。',
        mode: 'lines',
        targetCount: 5,
      },
      {
        id: 'selectedValue',
        label: '在候选池中选择最终版',
        helper: '选择最容易被复述的，而不是最宏大或最漂亮的。',
        placeholder: '我帮……',
        mode: 'long',
      },
    ],
    checks: ['包含帮谁', '包含具体问题', '包含推进结果', '没有内部术语', '能一口气说完'],
    sourcePages: '253–254',
  },
  {
    day: 5,
    stage: 1,
    title: '为什么客户想选择你？',
    principle: '“我很认真、我很专业、我有xx能力”是无法核验的，客户只会觉得“跟我有什么关系?”',
    output: '一句回答“为什么是你”的事实证据。',
    prep: ['做过的项目或产品', '交付物', '公开作品', '长期观察和实际结果'],
    prompts: [
      {
        id: 'evidenceFacts',
        label: '先列经验素材',
        helper: '列出与服务相关的过往经验，你做过什么、交付过什么。',
        placeholder: '我做过……\n我交付过……\n我长期处理……',
        mode: 'lines',
      },
      {
        id: 'evidenceSentence',
        label: '从素材中选择你的实力担当',
        placeholder: '我能做这件事，是因为……',
        mode: 'long',
      },
    ],
    checks: ['没有性格形容词', '事实可以核验', '与当前问题相关', '没有堆无关履历'],
    sourcePages: '254',
  },
  {
    day: 6,
    stage: 1,
    title: '你即将拥有一份服务说明',
    principle: '把前五天的选择拼成一个测试稿。它不是公开定稿，而是能拿到现实里接受反馈的当前版本。',
    output: '不超过 200 字的第一版品牌说明。',
    prep: ['价值句', '目标人群', '3 个问题', '证据句'],
    prompts: [
      {
        id: 'firstStatement',
        label: '检查并拼成你的服务说明',
        helper: '顺序：我帮谁、解决什么、让他能什么；适合谁；3 个常见问题；为什么是我。',
        placeholder: '我帮___，解决___，让他能___；我适合服务的人是___……',
        mode: 'long',
        maxChars: 200,
      },
    ],
    checks: ['不超过 200 字', '四项信息齐全', '没有新增未经验证的大词', '读起来像一个入口而不是简历'],
    sourcePages: '255',
  },
  {
    day: 7,
    stage: 1,
    title: '现实演练：发给身边 5 个人，看看他们如何理解',
    principle: '介绍是否清楚，不由你自己判断。不要解释，让别人直接复述，现实反馈才会暴露表达偏差。',
    output: '5 份复述反馈，以及一版按反馈修改的介绍。',
    prep: ['Day 6 的第一版说明', '5 位不太熟、但愿意说真话的人'],
    prompts: [
      {
        id: 'testers',
        label: '记录测试对象和反馈原话',
        mode: 'lines',
        targetCount: 5,
        placeholder: 'A / 前同事\nB / 同行……',
      },
      {
        id: 'retellFeedback',
        label: '判断哪些反馈值得采纳',
        helper: '分别问：你觉得我帮谁？解决什么？什么情况下会想到找我？',
        mode: 'long',
        placeholder: 'A 复述为……\nB 认为……',
      },
      {
        id: 'revisedStatement',
        label: '确定最终稿',
        mode: 'long',
        maxChars: 200,
      },
    ],
    checks: ['记录了测试对象', '保留了反馈原话', '辨别了值得采纳的反馈', '完成最终稿'],
    sourcePages: '255–257',
  },
  {
    day: 8,
    stage: 2,
    title: '整理作品证据',
    principle: '证据不是奖章，而是降低陌生人选择风险的台阶。先把做出来过的东西全部找回来。',
    output: '作品清单；每项都标明解决什么、证明什么。',
    prep: ['旧文章、产品、课程、手册', '服务方案、公开分享、可见交付物'],
    prompts: [
      {
        id: 'workEvidence',
        label: '先列作品，再逐项补充证据',
        mode: 'long',
      },
    ],
    checks: ['先列全再筛选', '每项都有问题', '每项都有证明含义', '能被别人看见或理解'],
    sourcePages: '259–260',
  },
  {
    day: 9,
    stage: 2,
    title: '写变化',
    principle: '结果不只是大数字。对客户真正有意义的是事情发生了什么具体变化。',
    output: '每项作品带来的具体变化。',
    prep: ['项目复盘', '前后版本', '客户行为或表达发生的变化'],
    prompts: [
      {
        id: 'resultEvidence',
        label: '为每项作品写出“从什么到什么”',
        placeholder: '从介绍自己很散，到能说清服务对象',
        mode: 'long',
      },
    ],
    checks: ['描述了变化', '足够具体', '没有夸大', '与作品相关'],
    sourcePages: '260–261',
  },
  {
    day: 10,
    stage: 2,
    title: '整理反馈',
    principle: '“很专业、很有帮助”是弱反馈。真正有用的反馈会说明对方具体理解了什么、改变了什么。',
    output: '一组能说明你解决了什么的具体反馈。',
    prep: ['聊天记录、评论', '转介绍原话、客户复盘、读者私信'],
    prompts: [
      {
        id: 'specificFeedback',
        label: '摘录具体反馈',
        helper: '使用别名并移除可识别信息。',
        placeholder: '反馈原话｜它证明我解决了什么',
        mode: 'long',
      },
    ],
    checks: ['不是泛泛夸奖', '能看出具体变化', '已移除敏感身份', '与主问题相关'],
    sourcePages: '261–262',
  },
  {
    day: 11,
    stage: 2,
    title: '整理认知变化，证明你的判断能力',
    principle: '从做过的事情中提炼认知变化，让别人知道你的判断从哪里来。',
    output: '一组能够证明判断来源的认知变化。',
    prep: ['职业变化、作品经历、失败或转折', 'Day 8–10 的证据材料'],
    prompts: [
      {
        id: 'stories',
        label: '选择作品，写出“以前—发现—现在”',
        placeholder: '我以前……后来我发现……所以我现在……',
        mode: 'long',
      },
    ],
    checks: ['写出了认知变化', '每段只有一个判断', '没有写成长篇自传'],
    sourcePages: '262',
  },
  {
    day: 12,
    stage: 2,
    title: '暂时留空',
    principle: '这一版暂时跳过第 12 天。',
    output: '本关暂不产出内容。',
    prep: [],
    prompts: [],
    checks: [],
    sourcePages: '263',
  },
  {
    day: 13,
    stage: 2,
    title: '选出代表作品，写一页“为什么能信我”',
    principle: '证据不是越多越好，而是越相关越有力。只保留最能支持当前主问题的作品。',
    output: '1–3 个代表作品，以及一页“为什么能信我”。',
    prep: ['Day 8 的作品清单', 'Day 1–7 确定的当前主问题'],
    prompts: [
      {
        id: 'representativeWorks',
        label: '选 1–3 个代表作品',
        helper: '每个回答：这是什么 / 解决什么 / 证明我什么。',
        placeholder: '01｜作品名｜解决……｜证明……',
        mode: 'long',
      },
      {
        id: 'trustPage',
        label: '生成一页“为什么能信我”',
        mode: 'long',
      },
    ],
    checks: ['选择了 1–3 个作品', '与当前问题相关', '作品内容清楚', '承诺边界明确'],
    sourcePages: '263–265',
  },
  {
    day: 14,
    stage: 2,
    title: '已合并到第 13 关',
    principle: '第 13 天已经同时完成代表作品和信任说明。',
    output: '沿用第 13 关生成的信任说明。',
    prep: [],
    prompts: [],
    checks: [],
    sourcePages: '264–265',
  },
  {
    day: 15,
    stage: 3,
    title: '写问题型内容',
    principle: '问题型内容先让读者认出自己。不要从你想讲什么开始，而从他误以为自己卡在哪里开始。',
    output: '一篇 800–1200 字的问题型内容初稿。',
    prep: ['3 个核心问题', '你的判断理由', '读者现在可以先做的一步'],
    prompts: [
      { id: 'problemTitle', label: '标题', placeholder: '你不是___，你是___。', mode: 'text' },
      { id: 'problemBelief', label: '第一段：写读者以为的问题', mode: 'long' },
      { id: 'problemTruth', label: '第二段：写真正的问题', mode: 'long' },
      { id: 'problemReason', label: '第三段：写你为什么这样判断', mode: 'long' },
      { id: 'problemAction', label: '第四段：写他现在先做什么', mode: 'long' },
    ],
    checks: ['读者能认出自己', '指出了真实问题', '有判断依据', '给出具体动作'],
    sourcePages: '267–268',
  },
  {
    day: 16,
    stage: 3,
    title: '写判断型内容',
    principle: '判断型内容要展示取舍：先做什么、暂时不做什么。可以锋利，但不要靠批判读者证明自己聪明。',
    output: '一篇展示取舍与工作方式的判断型内容。',
    prep: ['一个常见错误动作', '你更建议的顺序', '读者可以马上做的动作'],
    prompts: [
      { id: 'judgmentTitle', label: '标题', placeholder: '别先___，先___。', mode: 'text' },
      { id: 'judgmentCommon', label: '第一段：写大多数人会怎么做', mode: 'long' },
      { id: 'judgmentProblem', label: '第二段：写这样做的问题是什么', mode: 'long' },
      { id: 'judgmentAdvice', label: '第三段：写你现在更建议怎么做', mode: 'long' },
      { id: 'judgmentAction', label: '第四段：给一个具体动作', mode: 'long' },
    ],
    checks: ['有明确取舍', '解释了原因', '不羞辱读者', '给出具体动作'],
    sourcePages: '268–269',
  },
  {
    day: 17,
    stage: 3,
    title: '写故事型内容',
    principle: '故事的任务不是让人了解你的全部，而是让人知道一个判断从哪里来。',
    output: '一篇由经历落到判断的故事型内容。',
    prep: ['Day 11 的 5 段故事', '与当前主问题最相关的一段'],
    prompts: [
      { id: 'storyTitle', label: '标题', mode: 'text' },
      { id: 'storyBefore', label: '第一段：写“我以前……”', mode: 'long' },
      { id: 'storyDiscovery', label: '第二段：写“后来我发现……”', mode: 'long' },
      { id: 'storyNow', label: '第三段：写“所以我现在……”', mode: 'long' },
    ],
    checks: ['不是自传', '经历与读者有关', '落到了一个判断', '能支持当前主问题'],
    sourcePages: '269–270',
  },
  {
    day: 18,
    stage: 3,
    title: '写证据型内容',
    principle: '证据要服务判断。不要把履历摆成展览，而要解释这件作品为什么与读者眼前的问题有关。',
    output: '一篇“做过—解决—判断—读者用途”的证据型内容。',
    prep: ['作品、过程、结果、反馈或公开经验中的一个'],
    prompts: [
      { id: 'evidenceTitle', label: '标题', mode: 'text' },
      { id: 'contentEvidenceDid', label: '第一段：写我做过什么', mode: 'long' },
      { id: 'contentEvidenceSolved', label: '第二段：写它解决了什么问题', mode: 'long' },
      { id: 'contentEvidenceJudgment', label: '第三段：写它让我形成了什么判断', mode: 'long' },
      { id: 'contentEvidenceUse', label: '第四段：写这个判断对读者有什么用', mode: 'long' },
    ],
    checks: ['不堆履历', '证据与判断相连', '解释了读者用途', '不夸大结果'],
    sourcePages: '270–271',
  },
  {
    day: 19,
    stage: 3,
    title: '写产品入口型内容',
    principle: '内容不能只把人留在“有道理”。今天先写购买入口的雏形，下一阶段再用现实反馈把它定下来。',
    output: '一篇服务说明雏形。',
    prep: ['最可能需要帮助的人', '他最急的卡点', '你能推进的一步与具体交付'],
    prompts: [
      { id: 'offerTitle', label: '标题', mode: 'text' },
      { id: 'offerFit', label: '第一段：写谁适合', mode: 'long' },
      { id: 'offerProblem', label: '第二段：写他现在卡在哪里', mode: 'long' },
      { id: 'offerCost', label: '第三段：写这件事不解决会继续发生什么', mode: 'long' },
      { id: 'offerHelp', label: '第四段：写我能帮你完成哪一步', mode: 'long' },
      { id: 'offerDeliverable', label: '第五段：写具体交付什么', mode: 'long' },
      { id: 'offerNotFit', label: '第六段：写不适合谁', mode: 'long' },
      { id: 'offerStart', label: '第七段：写怎么开始', mode: 'long' },
    ],
    checks: ['先写问题再写产品', '交付物具体', '包含不适合谁', '下一步行动清楚'],
    sourcePages: '271–272',
  },
  {
    day: 20,
    stage: 3,
    title: '统一检查 5 篇内容',
    principle: '五篇内容不是为了凑齐五个类型，而是共同把你和一个问题连接起来。跑偏的内容要舍得删。',
    output: '一份跨内容检查结果，以及需要重写的清单。',
    prep: ['Day 15–19 的五篇初稿'],
    prompts: [
      {
        id: 'contentAudit',
        label: '用 Prompt 检查五篇内容',
        mode: 'long',
      },
    ],
    checks: ['五篇共同指向一个问题', '每篇都有判断', '每篇都有动作', '入口型内容没有提前过度承诺'],
    sourcePages: '272',
  },
  {
    day: 21,
    stage: 3,
    title: '发布并收集反馈',
    principle: '先发 2–3 篇，不要一次全发。点赞是弱反馈，具体提问、转发、咨询与购买意向才会推动下一步。',
    output: '2–3 篇发布记录，以及四类硬反馈。',
    prep: ['五篇初稿', '最适合测试的 2–3 篇', '发布渠道'],
    prompts: [
      { id: 'publishedContent', label: '发布了什么、发在哪里', mode: 'long' },
      {
        id: 'contentFeedback',
        label: '记录四类反馈',
        helper: '认出自己 / 追问具体问题 / 转发给需要的人 / 询问你能否帮做。',
        mode: 'long',
      },
      { id: 'contentRevision', label: '根据硬反馈准备改什么', mode: 'long' },
    ],
    checks: ['发布 2–3 篇', '记录四类反馈', '没有只看点赞', '把反馈带入下一阶段'],
    externalAction: '发布 2–3 篇内容，记录具体问题、私信、转介绍与购买意向。',
    sourcePages: '273–274',
    editorialNote: '原书写“记录三类反馈”，随后实际列出四类；Demo 按列出的四类呈现。',
  },
  {
    day: 22,
    stage: 4,
    title: '这一轮，你准备卖什么？',
    principle: '先选当前最能交付的小结果，不要先设计完整产品线。答不上“凭什么、解决什么、多久完成”，就继续缩小。',
    output: '一个最小购买入口及选择理由。',
    prep: ['前三阶段的介绍、证据与内容', '你能在 1–2 周内完成的交付'],
    prompts: [
      { id: 'offerCandidates', label: '列出当前可卖的小结果', mode: 'lines' },
      {
        id: 'chosenOffer',
        label: '选一个，并回答四个问题',
        helper: '为何现在卖 / 有什么证据 / 解决哪个问题 / 能否 1–2 周完成。',
        mode: 'long',
      },
    ],
    checks: ['只选一个', '解决具体问题', '已有交付证据', '1–2 周能完成'],
    sourcePages: '276–277',
  },
  {
    day: 23,
    stage: 4,
    title: '谁适合，谁不适合？',
    principle: '购买入口的第一屏先筛选匹配。边界不是赶走客户，而是减少错配，让交付更稳定。',
    output: '清楚的适合人群与不适合人群。',
    prep: ['Day 22 的最小产品', '你最能帮助的人', '你不提供的需求类型'],
    prompts: [
      { id: 'fitAudience', label: '适合谁', placeholder: '适合……', mode: 'long' },
      { id: 'notFitAudience', label: '不适合谁', placeholder: '不适合……', mode: 'long' },
    ],
    checks: ['能想起具体的人', '不是“所有人”', '不适合条件可判断', '没有羞辱不适合者'],
    sourcePages: '277–278',
  },
  {
    day: 24,
    stage: 4,
    title: '客户买完会拿到什么？',
    principle: '不要只写服务名字。客户需要知道问题会被推进到哪一步，以及结束时手里具体多出什么。',
    output: '一个明确问题，以及可以清点的交付物。',
    prep: ['目标人群最急的问题', '你实际能交付的文档、修改、结果或页面'],
    prompts: [
      { id: 'offerProblem', label: '重点解决什么问题', mode: 'long' },
      { id: 'deliverables', label: '对方会拿到什么', mode: 'lines' },
    ],
    checks: ['问题具体', '交付物可清点', '没有使用宽泛策略词', '没有承诺无法控制的结果'],
    sourcePages: '278–279',
  },
  {
    day: 25,
    stage: 4,
    title: '服务怎么进行，边界在哪里？',
    principle: '流程越清楚，购买风险越低。边界不是减少价值，而是让双方知道什么包含、什么不包含。',
    output: '清楚的交付步骤、包含项、不包含项和结果边界。',
    prep: ['实际交付顺序', '所需材料', '沟通次数、交付时间、修改次数'],
    prompts: [
      { id: 'process', label: '交付流程', placeholder: '第一步……第二步……', mode: 'long' },
      { id: 'included', label: '包含什么', mode: 'lines' },
      { id: 'excluded', label: '不包含什么、不承诺什么', mode: 'lines' },
    ],
    checks: ['每一步可执行', '时间与次数明确', '包含项清楚', '不包含和不承诺清楚'],
    sourcePages: '279–280',
  },
  {
    day: 26,
    stage: 4,
    title: '价格是多少，为什么值？',
    principle: '价格不能孤零零出现。先让对方看懂他购买的结果、证据与边界，再解释为什么不是只买你的时间。',
    output: '一个公开价格，以及与结果相连的价值说明。',
    prep: ['交付物、流程、边界', '不解决问题可能继续付出的成本'],
    prompts: [
      { id: 'price', label: '价格', placeholder: '¥ / 次 / 期', mode: 'text' },
      {
        id: 'priceRationale',
        label: '为什么值',
        helper: '回答：拿到什么 / 为什么不只是买时间 / 会少走什么弯路。',
        mode: 'long',
      },
    ],
    checks: ['价格没有隐藏', '价值与结果相关', '不是靠堆赠品', '边界与价格匹配'],
    sourcePages: '280',
  },
  {
    day: 27,
    stage: 4,
    title: '把购买入口拼出来',
    principle: '购买页不需要证据仓库，只需要最相关的几条。每条都要替读者解释：它为什么与这次选择有关。',
    output: '一组经过筛选并解释过的购买证据。',
    prep: ['Day 8–14 的证据、故事和代表作品'],
    prompts: [
      {
        id: 'offerEvidence',
        label: '放入最相关的证据',
        placeholder: '证据｜它证明什么｜与本产品的关系',
        mode: 'long',
      },
    ],
    checks: ['数量克制', '每条都解释证明含义', '与产品直接相关', '隐私安全'],
    sourcePages: '281',
  },
  {
    day: 28,
    stage: 4,
    title: '发给最可能购买的人',
    principle: '先不要大范围发布。把入口交给最可能需要的人，看他是否愿意付费，并认真听“不买”的原因。',
    output: '5 位高购买可能用户的真实反应。',
    prep: ['已经完整的购买入口', '5 位最可能需要这个结果的人'],
    prompts: [
      {
        id: 'buyerTesters',
        label: '列出 5 位测试者（只记别名）',
        mode: 'lines',
        targetCount: 5,
      },
      {
        id: 'purchaseResults',
        label: '记录是否购买，以及不购买的原因',
        mode: 'long',
      },
    ],
    checks: ['直接发给了 5 人', '询问了真实购买意愿', '无人购买时追问原因', '没有急着说服'],
    externalAction: '把购买入口私发给 5 位高购买可能用户，记录是否愿意付费及原因。',
    sourcePages: '281–282',
    editorialNote: '原书此处写 5 人，但下一天和周检写 10 人；Demo 将它整理成两轮各 5 人。',
  },
  {
    day: 29,
    stage: 4,
    title: '只按重复反馈修改',
    principle: '不要被一个人的意见带着全部推翻。把两轮共 10 人的反馈放在一起，只改重复出现的理解和购买障碍。',
    output: '重复反馈清单，以及修改后的购买入口。',
    prep: ['第一轮理解/需求测试 5 人', '第二轮高购买可能测试 5 人'],
    prompts: [
      {
        id: 'allFeedback',
        label: '汇总两轮共 10 人反馈',
        helper: '交付不清 / 适配不清 / 证据不足 / 开始方式不清 / 边界误解 / 有启发但不付费。',
        mode: 'long',
      },
      { id: 'repeatedSignals', label: '圈出重复出现的信号', mode: 'lines' },
      { id: 'offerRevision', label: '记录这次具体修改', mode: 'long' },
    ],
    checks: ['累计反馈达到 10 人', '按重复信号而非单人意见修改', '删掉含糊词', '补上缺失信息'],
    externalAction: '如第一轮尚未完成，补做 5 人理解/需求测试，使两轮反馈累计达到 10 人。',
    sourcePages: '282–283',
    editorialNote: '两轮各 5 人是对原书 5 人与 10 人数字跳跃的产品化整理。',
  },
  {
    day: 30,
    stage: 4,
    title: '正式放出你的第一版',
    principle: '发布时不要只说“上线新产品”。说清它帮谁解决什么问题，让合适的人知道下一步从哪里进入。',
    output: '正式发布的第一版购买入口，以及现实结果记录。',
    prep: ['修改后的购买入口', '主页、置顶、文末、简介或私信回复等发布位置'],
    prompts: [
      { id: 'launchLocations', label: '准备放在哪些位置', mode: 'lines' },
      {
        id: 'launchCopy',
        label: '写发布说明',
        helper: '说明帮谁、解决什么、如何开始；不要只宣布“新产品上线”。',
        mode: 'long',
      },
      { id: 'marketResult', label: '发布后的真实反应', mode: 'long' },
    ],
    checks: ['产品明确', '适合与不适合清楚', '问题和交付清楚', '流程、边界、价格齐全', '证据相关', '完成两轮测试', '记录是否有人愿意付费'],
    externalAction: '把第一版放到至少一个真实入口，观察具体咨询、购买和不购买原因。',
    sourcePages: '283–284',
  },
];
